const keysList = ["Cb", "Gb", "Db", "Ab", "Eb", "Bb", "F", "C", "G", "D", "A",
  "E", "B", "F#", "C#", "Abm", "Ebm", "Bbm", "Fm", "Cm", "Gm", "Dm", "Am",
  "Em", "Bm", "F#m", "C#m", "G#m", "D#m", "A#m"
]

const instrumentList = [
  "Accordion",
  "Acoustic guitar",
  "Bagpipes",
  "Banjo",
  "Bass guitar",
  "Bassoon",
  "Bongo",
  "Cello",
  "Clarinet",
  "Clavichord",
  "Cymbal",
  "Didgeridoo",
  "Double bass",
  "Drums",
  "Electric guitar",
  "Fiddle",
  "Flute",
  "French horn",
  "Glass harmonica",
  "Glockenspiel",
  "Gong",
  "Guitar",
  "Harmonica",
  "Harp",
  "Harpsichord",
  "Kalimba",
  "Lute",
  "Lyre",
  "Mandolin",
  "Marimba",
  "Oboe",
  "Ocarina",
  "Organ",
  "Oud",
  "Pan pipes",
  "Piano",
  "Piccolo",
  "Recorder",
  "Santoor",
  "Saxophone",
  "Sitar",
  "Synthesizer",
  "Table",
  "Tambourine",
  "Timpani",
  "Triangle",
  "Trombone",
  "Trumpet",
  "Theremin",
  "Tuba",
  "Ukulele",
  "Viola",
  "Violin",
  "Xylophone"
]

const genreList = [
  "Acid",
  "Alternative",
  "Ambient",
  "Bassline",
  "Bebop",
  "Black metal",
  "Breakbeat",
  "Britpop",
  "Celtic",
  "Chillwave",
  "Chiptune",
  "Christian",
  "Deep house",
  "Disco",
  "Downtempo",
  "Dream pop",
  "Drone",
  "Drum and bass",
  "Dubstep",
  "EDM",
  "Electro",
  "Electronic rock",
  "Emo",
  "Ethereal wave",
  "Eurobeat",
  "Experimental rock",
  "Folk",
  "Freestyle",
  "Funk",
  "Futurepop",
  "Garage rock",
  "Glam rock",
  "Glitch",
  "Grime",
  "Grunge",
  "Hardstyle",
  "Heavy metal",
  "Hip-hop",
  "House",
  "IDM",
  "Indie",
  "Industrial",
  "Italo",
  "Jazz",
  "Latin",
  "Lo-fi",
  "Minimal",
  "Moombahton",
  "Neo-psychedelia",
  "Neofolk",
  "New wave",
  "New-age",
  "Noise",
  "Nu jazz",
  "Nu metal",
  "Nu skool breaks",
  "Nu-disco",
  "Orchestral",
  "Pop",
  "Post-rock",
  "Progressive",
  "Psychedelic",
  "Punk rock",
  "Rock",
  "Screamo",
  "Shoegaze",
  "Ska",
  "Surf rock",
  "Swing",
  "Synthpop",
  "Techno",
  "Trance",
  "Trap",
  "Tribal house",
  "Trip hop",
  "Vaporwave",
  "Viking metal"
]

module.exports = {
  keys: keysList,
  instruments: instrumentList,
  genres: genreList
}
